name: starter_forge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

  # Network & HTTP
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Data & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utilities
  logger: ^2.0.2
  intl: ^0.20.2

  # Form validation
  formz: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Testing
  bloc_test: ^9.1.6
  mocktail: ^1.0.3
  flutter_lints: ^5.0.0

  # Code generation
  freezed: ^2.4.7
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Localization
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  generate: true

  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700